version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: <your_user>
      POSTGRES_PASSWORD: <your_password>
      POSTGRES_DB: <your_db_name>
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://postg<your_user>res:<your_password>@db:5432/<your_db_name>
    depends_on:
      - db